# default config: https://github.com/troessner/reek/blob/master/docs/defaults.reek.yml
# detectors' docs: https://github.com/troessner/reek/tree/master/docs
---
exclude_paths:
  - 'bin/'
  - 'spec/'

detectors:
  IrresponsibleModule:
    enabled: false
