require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false
